# Pandas Basic

### Pandas is a wrapper of 2 languages:
- numpy - numerical data and mathematical operations
- matplotlib - data visualization

In [1]:
import numpy as np
import pandas as pd

In [2]:
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')

Pandas: 3.0.2
Numpy: 2.4.4

### Pandas Datastructures
- Series - single dimensional datastructure. Similare to a list or a single column
    - homogeneous(of the same data type)
- DataFrame - multidimensional table
    - heterogeneous (of many datatypes)

In [3]:
ser1 = pd.Series([10, 20, 30, 40])
print(ser1)

ser1.iloc[0]

0    10
1    20
2    30
3    40
dtype: int64

np.int64(10)

In [4]:
# Creating a series from a preexistiong dictionary
d = {
    "b" : 1,
    "a" : 0,
    "c" : 2,
    "d" :100
}
ser2 = pd.Series(d)

In [5]:
d1 = {
    "a" : 0.0,
    "b" : 1.0,
    "c" :2.0
}
ser3 = pd.Series(d1)
# ser3 = pd.Series(d1, index = ["apple", 'banana', 'carrot'])
print(ser3)

a    0.0
b    1.0
c    2.0
dtype: float64

In [6]:
calories = {
    'day1 : 700,'
    'day2' :2500,
    'day3' :1200
}

#use indexes to chose certain values for series
ser4 = pd.Series(calories, index=['day1', 'day3'])
print(ser4)

day1       NaN
day3    1200.0
dtype: float64

In [7]:
# IF provided a scalar values, value will repeat to fill all index labels
ser5 = pd.Series(5.0, index=['a', 'b', 'c'])
print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

### Data Frames:
- indexes (each record)
- columns (each variable)

In [8]:
fruit_data = {
    'apple_sales': [3, 2, 0, 2, 9, 4, 7, 2],
    'orange_sales': [0, 3, 2, 7, 7, 8, 3, 0 ]
}

#dx = [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007]
idx = pd.RangeIndex(2000, 2008) #Dynamically create a range of indexes

#purchases = pd.DataFrame(fruit_data, index=['Day1', 'Day2', 'Day3', 'Day4', 'Day5', 'Day6', 'Day7', 'Day8'])
purchases = pd.DataFrame(fruit_data, index=idx)
print(purchases)

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

In [9]:
rows, cols = purchases.shape
print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 8
Cols: 2

In [10]:
# To view the top n elements, by default gives 5 elements
print(purchases.head())

      apple_sales  orange_sales
2000            3             0
2001            2             3
2002            0             2
2003            2             7
2004            9             7

In [11]:
# To view the bottom n elements, by default 5
print(purchases.tail())

      apple_sales  orange_sales
2003            2             7
2004            9             7
2005            4             8
2006            7             3
2007            2             0

### Importing Files with Pandas
- `.read_csv()`
- `.read_excel()`
- `.read_json()`
- `.read_sql()`

In [12]:
# Read employee into and pandas df
employee_df = pd.read_csv('data/employee.csv')

employee_df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [13]:
rows, cols = employee_df.shape
print('Rows:', rows)
print('Cols:', cols)

Rows: 15
Cols: 4

In [14]:
employee_df.dtypes

Name          str
Age       float64
Weight    float64
Salary    float64
dtype: object

In [15]:
# Importing JSON data
cars_df = pd.read_json('data/cars.json')
cars_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [16]:
cars_df.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

### EDA - Exploratory Data Analysis - The first look - The first look (Step 1 of data prep)
- Data Profiling
    - Structure (shape)
    - Quality (missing values, duplicates, unique values)
    - Content (data types, ranges, dispersion, measure central tendency)

- Profiling Techniques
    - Data Type and Format Validation
    - Statistical summaries(descriptive stats, values counts, frequency checks)
    - Uniqueness and Cardinality
    - Pattern Recognition
    - Cross0validation

In [17]:
rows, cols = cars_df.shape
print('Rows:', rows)
print('Cols:', cols)

Rows: 161
Cols: 11

In [18]:
cars_df.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

In [19]:
# Getting a brief overview of descriptive statistics (Quantitative Data)
cars_df.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [20]:
# Value counts of categoracal data
cars_df['city'].value_counts()

city
NewYork    36
NJ         35
DALLAS     33
TEXAS      30
OH         27
Name: count, dtype: int64

In [21]:
cars_df['city'].unique()

<StringArray>
['NJ', 'DALLAS', 'TEXAS', 'OH', 'NewYork']
Length: 5, dtype: str

In [22]:
cars_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           161 non-null    str
 1   MPG           161 non-null    float64
 2   Cylinders     161 non-null    int64
 3   Displacement  161 non-null    float64
 4   Horsepower    161 non-null    int64
 5   Weight        161 non-null    int64
 6   Acceleration  161 non-null    float64
 7   Model         161 non-null    int64
 8   Origin        161 non-null    str
 9   quantity      161 non-null    int64
 10  city          161 non-null    str
dtypes: float64(3), int64(5), str(3)
memory usage: 14.0 KB

In [23]:
cars_df.count()

Car             161
MPG             161
Cylinders       161
Displacement    161
Horsepower      161
Weight          161
Acceleration    161
Model           161
Origin          161
quantity        161
city            161
dtype: int64

In [24]:
cars_df.head(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS

In [25]:
cars_df.tail(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
159,Mercury Lynx l,36.0,4,98.0,70,2125,17.3,82,US,425,TEXAS
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH

In [26]:
# .at method to grab specific values from dataset using the label
cars_df.at[159, 'MPG']

np.float64(36.0)

In [27]:
cars_df.iloc[159]

Car             Mercury Lynx l
MPG                       36.0
Cylinders                    4
Displacement              98.0
Horsepower                  70
Weight                    2125
Acceleration              17.3
Model                       82
Origin                      US
quantity                   425
city                     TEXAS
Name: 159, dtype: object

In [28]:
# .at method to grab specific values from dataset using the index number
cars_df.iat[159, 1]

np.float64(36.0)

In [29]:
cars_df.size

1771

In [30]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}
student_df = pd.DataFrame(student_dict)
student_df.head()

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

In [31]:
student_df.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [32]:
list_Index = student_df.columns
print('Columns Names', list_Index)

Columns Names Index(['Name', 'Age', 'Marks'], dtype='str')

In [33]:
label = student_df.columns[0]
print(label)

Name

In [34]:
# Getting column names as list for looping
labels_as_list = student_df.columns.to_list()
print(labels_as_list)

['Name', 'Age', 'Marks']

### EDA w/CSV

e_df.head()

In [35]:
e_df = pd.read_csv('data/employee.csv')

In [36]:
e_df.head(10)

       Name   Age  Weight     Salary
0     James  36.0    75.0  5428000.0
1   Villers  38.0    74.0  3428000.0
2     VKole  31.0    70.0  8428000.0
3     Smith  34.0    80.0  4428000.0
4     Gayle  40.0   100.0  4528000.0
5      Adam  40.0     NaN  4528000.0
6    Rooter  33.0    72.0  7028000.0
7  Peterson  42.0    85.0  2528000.0
8     lynda  42.0    85.0        NaN
9       NaN  42.0    85.0        NaN

In [37]:
e_df.tail(2)

    Name   Age  Weight     Salary
13  John  41.0    85.0  1528000.0
14   Ali  26.0    69.0        NaN

In [38]:
e_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    14 non-null     str
 1   Age     12 non-null     float64
 2   Weight  14 non-null     float64
 3   Salary  12 non-null     float64
dtypes: float64(3), str(1)
memory usage: 612.0 bytes

In [39]:
rows, cols = e_df.shape
print('Rows:', rows)
print('Cols:', cols)

Rows: 15
Cols: 4

In [40]:
e_df2 = pd.read_csv('data/employee.csv', skiprows=5, header=None)
e_df2

           0     1      2          3
0      Gayle  40.0  100.0  4528000.0
1       Adam  40.0    NaN  4528000.0
2     Rooter  33.0   72.0  7028000.0
3   Peterson  42.0   85.0  2528000.0
4      lynda  42.0   85.0        NaN
5        NaN  42.0   85.0        NaN
6      Jenny   NaN  100.0    25632.0
7       Kenn   NaN  110.0    25632.0
8        Aly   NaN   90.0    25582.0
9       John  41.0   85.0  1528000.0
10       Ali  26.0   69.0        NaN

In [41]:
# Get only specific columns from CSV
# e_df3 = pd.read_csv('data/employee.csv', usecols=['Name', 'Salary']) #based on labels
e_df3 = pd.read_csv('data/employee.csv', usecols=[0, 3]) #based on index numbers
e_df3

        Name     Salary
0      James  5428000.0
1    Villers  3428000.0
2      VKole  8428000.0
3      Smith  4428000.0
4      Gayle  4528000.0
5       Adam  4528000.0
6     Rooter  7028000.0
7   Peterson  2528000.0
8      lynda        NaN
9        NaN        NaN
10     Jenny    25632.0
11      Kenn    25632.0
12       Aly    25582.0
13      John  1528000.0
14       Ali        NaN

### Selecting Columns

In [42]:
df_cars = pd.read_json('data/cars.json')
df_cars.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [43]:
# accessing single value, single brackets
df_cars.columns[0]

'Car'

In [44]:
# accessing multiple values, double brackets
df_cars.columns[[0, 1, 9]]

Index(['Car', 'MPG', 'quantity'], dtype='str')

In [45]:
# Accessing a Series using a label

df_cars['Car']

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [46]:
#Accessing a series with a index number
df_cars[df_cars.columns[0]]

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [47]:
df_cars[['Car', 'MPG','quantity']]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

In [48]:

# Grab subset of dataframe with index numbers
df_cars[df_cars.columns[[0,1,9]]]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

### Frequency Analysis - Value counts

In [49]:
# Sample DataFrame
data = {'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing']}
cat_df = pd.DataFrame(data)

# .value_counts
cat_df.value_counts()

Category
Electronics    2
Clothing       2
Books          2
Name: count, dtype: int64

In [50]:
# Create the dataframe
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
           'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
           'Sales':[1000,2000,4000,2000,1000,4000],
           'Profit':[500,1000,1000,1500,1000,1500],
           'Pices left':[5000,4000,4000,5000,5000,1000]}

sales_df = pd.DataFrame(sales_data)

Frequency = sales_df ['Brand'].value_counts()
#print(Frequency)

frequent_product = Frequency[Frequency > 1].index[0]

print(Frequency)
print(f'This item appears more than once: {frequent_product}')

Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
This item appears more than once: Samsung

In [51]:
data = {'Score': [85, 92, 88, 75, None, 90, None, 85]}
scores_df = pd.DataFrame(data)

In [52]:
scores_counts = scores_df.value_counts(dropna=False) #dropna, tells function to either include or NOT include Nan, Null, NA values
print('Score', scores_counts)

Score Score
85.0     2
NaN      2
92.0     1
88.0     1
75.0     1
90.0     1
Name: count, dtype: int64

### Rename a column in Pandas
- `.rename()`

In [53]:
tech = {
    'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
    'Fee': [100, 2000, 250, 300],
    'Duration':['40days', '50days', '3 months', '1 year']
}
tech_df = pd.DataFrame(tech)

In [54]:
tech_df = tech_df.rename(columns={'Courses': 'Course Name'})

In [55]:
tech_df.head()

        Course Name   Fee  Duration
0            Python   100    40days
1     DataAnalytics  2000    50days
2        MERN Stack   250  3 months
3  Data Engineering   300    1 year